service: xen-ai-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  timeout: 30
  environment:
    PORT: 5000
    NODE_ENV: development
    DB_HOST: srv945.hstgr.io
    DB_PORT: 3306
    DB_USER: u307442259_node
    DB_PASSWORD: 1ti36~$Q$+M
    DB_NAME: u307442259_node
    OPENROUTER_API_KEY: <OPENROUTER_API_KEY>
    FRONTEND_URL: https://master.ddcw2f5tf37tj.amplifyapp.com
    JWT_SECRET: xen-ai-jwt-secret-key-change-in-production-2024
    JWT_EXPIRES_IN: 7d
    HF_TOKEN: your-hugging-face-api-token

functions:
  api:
    handler: handler.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /

package:
  patterns:
    - '!**/*'
    - handler.cjs
    - app.js
    - package.json
    - node_modules/**
    # include a nested copy of project code into serverless bundle
    - ../config/**
    - ../routes/**
    - ../models/**
    - ../middleware/**
    - ../services/**
    - ../public/images/**
    # also include symlinked copies under serverless/ if present
    - config/**
    - routes/**
    - models/**
    - middleware/**
    - services/**
    - public/images/**
    - '!../node_modules/**'
